{"name": "test_bus207", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus207\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')", "trace": "self = <Test_MT.TestOther object at 0x00000254F58383C8>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_TTM_v5\")\n    def test_bus207(self):\n>       assert AutoTest(number, mac, name, '_P_TTM_v5', 'bus207') == True, \"Ошибка в ходе выполнения теста bus207\"\nE       AssertionError: Ошибка в ходе выполнения теста bus207\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')\n\nTest_MT.py:134: AssertionError"}, "attachments": [{"name": "log", "source": "c7f89e3c-c412-474d-b219-9e5c0b3e6fc2-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "f3507899-7f38-43f6-b66b-feb8fc72b316-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6b327c38-c69d-4032-a21e-8ed06241b0aa-attachment.txt", "type": "text/plain"}], "start": 1651787763379, "stop": 1651787953194, "uuid": "7f92697f-0643-4ba3-8c66-feef4cf00b5d", "historyId": "3369cd05539770f0c09511c571a4094b", "testCaseId": "bc0a014b62f50edbcb39f57be6bfbe2a", "fullName": "Test_MT.TestOther#test_bus207", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_TTM_v5"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}