{"name": "test_eos_beeline", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')", "trace": "self = <Test_MT.TestEOS object at 0x0000025DCC996630>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_beeline\")\n    def test_eos_beeline (self):\n>       assert AutoTest(number, mac, name, '_P_dit_beeline', 'beeline') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_beeline\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')\n\nTest_MT.py:86: AssertionError"}, "attachments": [{"name": "log", "source": "83b5903d-b63c-4e23-90ba-21e4887f96a5-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "419f1d74-5b4a-493e-a812-c9aa8160f78b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "bcb412b7-6282-47aa-8b32-3a0d731c2f0f-attachment.txt", "type": "text/plain"}], "start": 1652008433427, "stop": 1652008556756, "uuid": "776a33c7-f519-40b6-b1d0-45337e6368c0", "historyId": "e22ae9fe984354816df9ee71a888005b", "testCaseId": "6681ab98911e15b281dbcc8f74f0892b", "fullName": "Test_MT.TestEOS#test_eos_beeline", "labels": [{"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "story", "value": "Авторизация _P_dit_beeline"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}