{"name": "test_eos_beeline", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')", "trace": "self = <Test_MT.TestEOS object at 0x000001C0A19F4748>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_beeline\")\n    def test_eos_beeline (self):\n>       assert AutoTest(number, mac, name, '_P_dit_beeline', 'beeline') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_beeline\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')\n\nTest_MT.py:86: AssertionError"}, "attachments": [{"name": "log", "source": "cfdbd187-120f-4c17-be19-84ece7241fbe-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ba9d4d22-2eda-4d36-94b1-f8d58177a558-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "3a9da289-35ae-4e1f-b2f0-2c432b46c53d-attachment.txt", "type": "text/plain"}], "start": 1651970643414, "stop": 1651970861212, "uuid": "5cb6169e-e335-4d44-abb1-6e653e3ae4ff", "historyId": "e22ae9fe984354816df9ee71a888005b", "testCaseId": "6681ab98911e15b281dbcc8f74f0892b", "fullName": "Test_MT.TestEOS#test_eos_beeline", "labels": [{"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_dit_beeline"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}