{"name": "test_eos_beeline", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')", "trace": "self = <Test_MT.TestEOS object at 0x00000237B407FEF0>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_beeline\")\n    def test_eos_beeline (self):\n>       assert AutoTest(number, mac, name, '_P_dit_beeline', 'beeline') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_beeline\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')\n\nTest_MT.py:86: AssertionError"}, "attachments": [{"name": "log", "source": "c1724253-8d01-4472-b045-52bb42cc349e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ab096e4b-1b43-49f8-ba83-d1c5f1f9efc1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "16820c3e-af2d-4647-b125-81c85a4869f9-attachment.txt", "type": "text/plain"}], "start": 1651754485005, "stop": 1651754616412, "uuid": "b718819d-c727-46f2-bc9e-704bd449da38", "historyId": "e22ae9fe984354816df9ee71a888005b", "testCaseId": "6681ab98911e15b281dbcc8f74f0892b", "fullName": "Test_MT.TestEOS#test_eos_beeline", "labels": [{"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_dit_beeline"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}