{"name": "test_metro", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_metro\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_metro', 'metro')", "trace": "self = <Test_MT.TestOther object at 0x000002BF93380748>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_metro\")\n    def test_metro (self):\n>       assert AutoTest(number, mac, name, '_P_metro', 'metro') == True, \"Ошибка в ходе выполнения теста _P_metro\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_metro\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_metro', 'metro')\n\nTest_MT.py:101: AssertionError"}, "attachments": [{"name": "log", "source": "1629a708-9e6d-4015-9ac3-7b46082a971b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "10fb26df-575e-48e2-b166-b354bce95993-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "da6cb822-484b-4e19-8ba3-6d00746a6ab5-attachment.txt", "type": "text/plain"}], "start": 1651949348131, "stop": 1651949514283, "uuid": "981e372e-cdc5-4d07-8fc2-b0d035ba6a5a", "historyId": "8acea32337f99371ab552a6e37fcab1f", "testCaseId": "9d6c6d19f4d4c8de89bf750f8280ce72", "fullName": "Test_MT.TestOther#test_metro", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_metro"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "1476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}